# Eureka Discovery Service 내부 전용 설정 파일
server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

management:
  metrics:
    binder:
      processor:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
