spring:
  config:
    import: application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      # localhost 대신 도커 서비스 이름 사용
      defaultZone: http://discovery-service:8761/eureka/
    initial-instance-info-replication-interval-seconds: 40
    instance-info-replication-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
  instance:
    # Docker 환경에서 중요한 설정
    prefer-ip-address: true

jwt:
  expiration: 3600000
  refresh-expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG