server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: newsletter-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    bootstrap:
      enabled: false
  main:
    allow-bean-definition-overriding: true

# Actuator 엔드포인트 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# 로깅 설정
logging:
  level:
    com.newsletterservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger 설정
springdoc:
  api-docs:
    path: /newsletter-api-docs
  swagger-ui:
    path: /newsletter-swagger-ui.html

oauth2:
  redirect:
    frontend-callback-url: http://be09-final-1team-fe-env.eba-92qhhhzz.ap-northeast-2.elasticbeanstalk.com/auth/callback
    frontend-additional-info-url: http://be09-final-1team-fe-env.eba-92qhhhzz.ap-northeast-2.elasticbeanstalk.com/auth/additional-info
    frontend-additional-info-url: http://be09-final-1team-fe-env.eba-92qhhhzz.ap-northeast-2.elasticbeanstalk.com/auth/additional-info